version: "3.8"
services:
  bot:
    image: kamilfodeveloper/telegram-support-bot:latest
    restart: always
    env_file:
      - .env
    environment:
      - SA_DB_PROVIDER=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - bot_network

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - bot_network
    ports:
      - '5432:5432'

networks:
  bot_network:
    driver: bridge

volumes:
  db-data:


