"""Added caption column for attachments

Revision ID: 9701e090e266
Revises: 66d249607e0c
Create Date: 2023-02-05 10:50:53.371056

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '9701e090e266'
down_revision = '66d249607e0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers_attachmets', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('questions_attachmets', sa.Column('caption', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions_attachmets', 'caption')
    op.drop_column('answers_attachmets', 'caption')
    # ### end Alembic commands ###
