class States:
    BIND_ACTION = "BIND"
    UNBIND_ACTION = "UNBIND"
    ESTIMATE_AS_USEFUL_ACTION = "ESTIMATED_AS_USEFUL"
    ESTIMATE_AS_UNUSEFUL_ACTION = "ESTIMATED_AS_UNUSEFUL"
    SHOW_ATTACHMENTS_ACTION = "SHOW_ATTACHMENTS"
